name: Kafka based Weather Reporter Build
on:
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args: 
            build
